import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavbarApp from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Anime please",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <Providers>
          <NavbarApp />
          {children}
        </Providers>
      </body>
    </html>
  );
}
